### ISSUE TITLE
One-dimensional SoftBART

### ISSUE THREAD

**Issue by MateusMaiaDS** [theodds/SoftBART#5]
Hi there,

I was trying to use SoftBART over some univariate simulations but I couldn't due to this error: 

```
Error in glmnet(x, y, weights = weights, offset = offset, lambda = lambda,  : 
 x should be a matrix with 2 or more columns
```

Is there any easy way to solve this problem?

Best regards,

**Comment by theodds** [comment]
Hi Mateus,

Two things:

- A hacky way to get around this is to duplicate your single column. It will mostly be equivalent to applying SoftBART in the univariate setting; technically it will be slightly different, but not in any way that I think is meaningful. Alternatively, you can feed in a junk variable for the second column, turn off `update_s`, and zero out the `s` associated to the junk variable; this will actually be equivalent to using one variable, but it presumes a bit more on your part.
- If you have only a single variable you are feeding into the SoftBART, my general expectation is that you would be better served doing some sort of basis function expansion or using a univariate smoother. In particular, if you want to get the features that I think SoftBART would be useful for in one dimension without any of the headaches, something like a Daubechies wavelet using, say, a horseshoe or spike-and-slab prior on the wavelet coefficients, will probably do great for you. 
- I'm happy with the error, so that at least people think twice before using this in a univariate problem where there is likely something better to be done :) Of course, you may have a good reason for wanting to benchmark SoftBART specifically in this setting!
